### ISSUE TITLE
single statement is recorded multiple times in the clover covearge report 

### ISSUE THREAD

**Issue by soneyahossain** [openclover/clover#163]
I am using clover-maven plugin ( 4.4.1) to compute coverage for joda time. In the clover.xml file, I found 16 statements that are counted multiple times. Here is an example of the coverage and snap from the source file : 

```
   <line num="1076" count="46" type="stmt"/>
            <line num="1076" count="22" type="stmt"/>
            <line num="1076" count="18" type="stmt"/>
            <line num="1076" count="20" type="stmt"/>
            <line num="1076" count="40" type="stmt"/>
            <line num="1077" count="26" type="stmt"/>
            <line num="1077" count="0" type="stmt"/>
            <line num="1077" count="0" type="stmt"/>
            <line num="1077" count="22" type="stmt"/>


```

 1074                switch (periodStr.charAt(pos)) {
 1075                case '0': case '1': case '2': case '3': case '4':
 1076                case '5': case '6': case '7': case '8': case '9':
 1077                case '.': case ',': case '+': case '-':
                         break;
```
```

**Comment by marek-parfianowicz** [comment]
Hi! In my opinion this is a valid result. Please notice that you have several "case" conditions in a single source line (lines 1075-1077). Every case is a separate branch in a business logic (even if all of them are fall-throughs to the "break"). Therefore OpenClover tracks every case individually. Each case have different number of executions because of different inputs. In your case it's probably:

case 4 executed 18 times,
case 3 executed 20 times,
case 2 executed 22 times,
case 1 executed 40 times,
case 0 executed 46 times.
