### ISSUE TITLE
Migrate from Log4j v1.2 due to vulnerabilities in this library. Move to SLF4J 1.7.x.

### ISSUE THREAD

**Issue by abuSayedMohammad** [openclover/clover#165]
The latest version of openclover(v4.4.1) is using log4j v1.2.17. We have got below vulnerability in this log4j version:
1. CVE-2022-23305
2. CVE-2022-23307
3. CVE-2019-17571

Can you please update to latest version of log4j v2.x.x

**Comment by marek-parfianowicz** [comment]
This PR requires a rework. We can't use log4j 2.17.2, because OpenClover still supports JDK7. A safe version supporting this Java version is 2.12.4.

**Comment by marek-parfianowicz** [comment]
I decided to migrate from Log4j 1.2 to **SLF4J** instead of Log4j 2.x. 

One of the reasons is that the usage of Log4J was minimal in the code (only as a supplementary logger for recorder module). Another reason is that SLF4J is a very small facade, which allows to plug in practically any logging framework (java logging, logback, log4j 1 & 2). 

This means the Clover will detach from Log4J dependency and its vulnerabilities.
