### ISSUE TITLE
Instrumentation fails on switch cases with multiple entries

### ISSUE THREAD

**Issue by matic277** [openclover/clover#246]
Instrumentation fails with:

> ERROR: C:\Users\matica\IdeaProjects\CloverMultipleCases\src\main\java\org\example\Main.java:11:13:expecting COLON, found ','

When clover 4.5.2 processes switch statements.

I have created a simple project, where this is reproducable:
https://github.com/matic277/CloverMultipleCases

To reproduce the error, run gradle task _cloverInstr_.

Example from the linked repo:

```
public static void main(String[] args)
{
  switch (1)
  {
    case 0: System.out.println("ok"); break;
    case 1, 2: System.out.println("not ok"); break;
    case 3: System.out.println("ok"); break;
    default: throw new RuntimeException();
  }
}
```
this will fail with 
> ERROR: C:\Users\matica\IdeaProjects\CloverMultipleCases\src\main\java\org\example\Main.java:11:13:expecting COLON, found ','

However, this:
```
public static void main(String[] args)
{
  switch(1)
  {
    case 0, 1: break;
  }
}
```
will fail with
> ERROR: C:\Users\matica\IdeaProjects\CloverMultipleCases\src\main\java\org\example\Main.java:8:5:unexpected token: switch

which is also strange.

**Comment by marek-parfianowicz** [comment]
Thank you for reporting this problem.

I found a similar test for this, which is passing:

https://github.com/openclover/clover/blob/master/clover-core/src/test/resources/javasyntax14/Java14SwitchExpressionWithMultiValueCase.java

The difference is that it uses "case 0, 1 ->" syntax instead of "case 0, 1:". 

Can you confirm that your code snippet compiles without OpenClover, i.e. that this is really a valid java syntax?

Also, which Java version did you use?

Also, did you enable any experimental flags?


________________________________
From: matic277 ***@***.***>
Sent: Monday, March 4, 2024 10:29
To: openclover/clover
Cc: Subscribed
Subject: [openclover/clover] Instrumentation fails on switch cases with multiple entries (Issue #246)

Instrumentation fails with:
>
> ERROR: C:\Users\matica\IdeaProjects\CloverMultipleCases\src\main\java\org\example\Main.java:11:13:expecting COLON, found ','

When clover 4.5.2 processes switch statements.
I have created a simple project, where this is reproducable:
https://github.com/matic277/CloverMultipleCases
To reproduce the error, run gradle task cloverInstr.
Example from the linked repo:

public static void main(String[] args)
{
  switch (1)
  {
    case 0: System.out.println("ok"); break;
    case 1, 2: System.out.println("not ok"); break;
    case 3: System.out.println("ok"); break;
    default: throw new RuntimeException();
  }
}

this will fail with
>
> ERROR: C:\Users\matica\IdeaProjects\CloverMultipleCases\src\main\java\org\example\Main.java:11:13:expecting COLON, found ','

However, this:

public static void main(String[] args)
{
  switch(1)
  {
    case 0, 1: break;
  }
}

will fail with
>
> ERROR: C:\Users\matica\IdeaProjects\CloverMultipleCases\src\main\java\org\example\Main.java:8:5:unexpected token: switch

which is also strange.

**Comment by matic277** [comment]
I'm using Java 17 (Temurin 17.0.4), i'm on windows 10.
No experimental features enabled.

Yes, java code is valid, compiles and runs without any errors.
Also, i have tried:
```
case 0 -> System.out.println("test"); // clover instruments without any errors
case 0,1: System.out.println("test"); break; // error, expecting COLON, found ','
```

**Comment by marek-parfianowicz** [comment]
Thank you! In the meantime.I found the code responsible for it.

https://github.com/openclover/clover/blob/1b5e0f63430ceb0929ff8338aaa31fabb0893f5c/clover-core/src/main/java/org/openclover/core/instr/java/java.g#L2621

https://github.com/openclover/clover/blob/1b5e0f63430ceb0929ff8338aaa31fabb0893f5c/clover-core/src/main/java/org/openclover/core/instr/java/java.g#L2646


The current grammar allows to group several cases, e.g:

case 0:
case 1:
   doSomething();
   break;

And this is a workaround you can use.

I wasn't aware that "case 0, 1:" has been implemented in Java. I thought it allows "case 0, 1 ->" only.

Of course I will implement it for the upcoming release. Thank you for reporting this!!!

**Comment by matic277** [comment]
Yes, the workaround works, and it's currently what I've done with our prod code.

Thanks!

**Comment by marek-parfianowicz** [comment]
PR #254
